version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}

  streamlit:
    build: ./frontend_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env

  testsimulator:
    build: ./test-simulator
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      API_URL: ${API_URL}

volumes:
  postgres_data:
