# File: MyLearning/.github/workflows/run-ping-app-tests-ci.yml

name: CI Pipeline - Ping App

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo
                ports:
                    - 27017:27017

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install backend dependencies
              run: pip install -r Traffic_Simulator/ping-app/backend/requirements.txt

            - name: Install test dependencies
              run: pip install pytest pytest-qt PyQt5

            - name: Run tests
              working-directory: Traffic_Simulator/ping-app
              run: pytest tests/
